name: CI Test

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "test"
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  tuber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo Build
        run: cargo build --verbose --manifest-path tuber/Cargo.toml
      - name: Cargo Test
        run: cargo test --verbose --manifest-path tuber/Cargo.toml
  ski:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo Build
        run: cargo build --verbose --manifest-path ski/Cargo.toml
      - name: Cargo Test
        run: cargo test --verbose --manifest-path ski/Cargo.toml
